import type { Metadata } from "next";
import { Alata } from "next/font/google";
import localFont from "next/font/local";
import {Header} from "@/components/layout/Header";

const alata = Alata({
  variable: "--font-alata",
  subsets: ["latin"],
  weight: "400",
});


const sofiaPro = localFont({
  src: [
    {
      path: "../public/fonts/sofia-pro/SofiaPro-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/sofia-pro/SofiaPro-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sofia-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Marvel Power Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alata.variable} ${sofiaPro.variable} antialiased`}>
      <Header />
        {children}
      </body>
    </html>
  );
}
